on:
  push:
    tags:
    - 'v*'

name: Publish to NPM

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install || exit 1
      - run: yarn lint || exit 2
      - run: yarn test || exit 3
      - run: yarn build || exit 4
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
